#pragma once
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
//#include <shlwapi.h>
#include <stdexcept>
#include <string>
#include <vector>
#include <Windows.h>
//#include <psapi.h>

using std::string;
using std::to_string;
using std::wstring;
using std::to_wstring;
using std::wcout;
using std::endl;
using std::set;
using std::vector;
using std::map;
using std::ifstream;
using std::ofstream;
using std::filesystem::recursive_directory_iterator;
using std::filesystem::create_directory;
using std::filesystem::is_directory;
using std::filesystem::filesystem_error;
using std::exception;
using std::runtime_error;